/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();

  // Suzanne.gltf is in public folder
  const { nodes } = useGLTF("/suzanne.gltf");

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Suzanne.geometry}
        material={nodes.Suzanne.material}
        position={[0, 0.19, -0.04]}
      />
    </group>
  );
}
// Load the gltf into our scene
// Suzanne.gltf is in public folder
/* @react-three/drei exports a very useful helper useGLTF.  It acquires the object 
 * load methods from three, so all we need to do is pass it the location of our mesh */
useGLTF.preload("/suzanne.gltf");
